[app]
  name = "Ordexa"
  version = "1.0.1"

[db]
  host = "127.0.0.1"
  port = 5432
  user = "postgres"
  password = "postgres"
  database = "ordexa"
  [db.options]
    synchronize = true
    logging = false
  [db.pool]
    max = 10
    min = 2
    idleTimeoutMillis = 30000
    connectionTimeoutMillis = 2000
